# grupo 4 - kelly vílchez

## Tarea 4 :

* Crear el array utilizando los métodos utilizados en clase 

In [4]:
import numpy as np

#### Ejercicio 01 :

In [2]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [27]:
import numpy as np
tarea = np.arange(1,18,1)
tarea = np.arange(start = 1,stop = 18,step = 1)
tarea

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

####  Ejercicio 02 :
Crear un array de 4x4 con valores pares 

In [6]:
import numpy as np
C = np.array([[7,5,13],[37,9,3],[25,31,47],[1,7,3]])
C

array([[ 7,  5, 13],
       [37,  9,  3],
       [25, 31, 47],
       [ 1,  7,  3]])

#### Ejercicio 04 :
Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [10]:
import numpy as np
arbol = np.arange(0,32,1)
arbol = np.arange(start = 0,stop = 32,step = 1)
arbol

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [9]:
# verificamos que contenga 32 elementos
arbol.size

32

In [11]:
# posibles formas
arbol.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
arbol.reshape((4,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [13]:
arbol.reshape((2,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [14]:
arbol.reshape((16,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [15]:
arbol.reshape((32,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [16]:
arbol.reshape((1,32))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

#### Ejercicio 05 :
Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [17]:
import numpy as np
E = np.array ([[[4,8,10],[1,2,3],[5,23,3]],[[1,6,3],[8,2,5],[2,9,4]],[[56,6,1],[7,4,2],[11,4,7]]])
E

array([[[ 4,  8, 10],
        [ 1,  2,  3],
        [ 5, 23,  3]],

       [[ 1,  6,  3],
        [ 8,  2,  5],
        [ 2,  9,  4]],

       [[56,  6,  1],
        [ 7,  4,  2],
        [11,  4,  7]]])

In [18]:
E.size

27

In [19]:
E.shape

(3, 3, 3)

In [20]:
F= E.reshape(9,3)
F

array([[ 4,  8, 10],
       [ 1,  2,  3],
       [ 5, 23,  3],
       [ 1,  6,  3],
       [ 8,  2,  5],
       [ 2,  9,  4],
       [56,  6,  1],
       [ 7,  4,  2],
       [11,  4,  7]])

In [21]:
#Ubicar 10 elementos
F[[0,1,3,5,8,2,4,7,1,0],[1,0,0,1,2,0,0,2,2,0]]

array([8, 1, 1, 9, 7, 5, 8, 2, 3, 4])

#### Ejercicio 06 :
* Crear el array utilizando los metodos aprendidos en clase

In [22]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [23]:
tarea_1 =np.arange(0,25,1).reshape((5,5))
tarea_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
tostada =np.arange(0,8,1).reshape((4,2))
tostada

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
cafe= np.arange(0,4,1).reshape ((2,2))
cafe

array([[0, 1],
       [2, 3]])

In [26]:
desayuno=np.concatenate((tostada,cafe), axis = 0)
desayuno

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])