## Tarea 4 : Desarrollado por Raúl-Sedano

* Crear el array utilizando los métodos utilizados en clase 

In [4]:
import numpy as np

#### Ejercicio 01 :

In [17]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

####  Ejercicio 02 :

Crear un array de 4x4 con valores pares 

In [160]:
r = np.full((4,4),2)
print(rpta1)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [133]:
r1.size

16

In [134]:
r2 = np.arange(0,32,2).reshape(4,4)
r2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [135]:
r2.size

16

####  Ejercicio 03 :

Crear un array de 4x3 con valores impares

In [136]:
raa = np.full((4,3),7)
raa

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [137]:
raa.size

12

In [138]:
rb = np.array([[1,3,5,7],[9,11,13,15],[17,19,23,25]])
rb

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 23, 25]])

In [139]:
rb.size

12

In [140]:
rc = np.arange(1,25,2).reshape(4,3)
rc

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [141]:
rc.size

12

#### Ejercicio 04 :

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [38]:
a = np.arange(0,32,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [39]:
a.size

32

In [40]:
a.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [53]:
a.reshape((32,-6537))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [41]:
a1b = np.ones_like(a)
a1b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [52]:
a2 = np.diag(a)
a2

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 29,  0,  0],
       [ 0,  0,  0, ...,  0, 30,  0],
       [ 0,  0,  0, ...,  0,  0, 31]])

In [53]:
a3 = np.tril(a)
a3

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  1,  2, ...,  0,  0,  0],
       ...,
       [ 0,  1,  2, ..., 29,  0,  0],
       [ 0,  1,  2, ..., 29, 30,  0],
       [ 0,  1,  2, ..., 29, 30, 31]])

In [54]:
a4 = np.triu(a)
a4

array([[ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  0,  2, ..., 29, 30, 31],
       ...,
       [ 0,  0,  0, ..., 29, 30, 31],
       [ 0,  0,  0, ...,  0, 30, 31],
       [ 0,  0,  0, ...,  0,  0, 31]])

#### Ejercicio 05 :

Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [70]:
b = np.arange(10,550,20).reshape((3,3,3))
b

array([[[ 10,  30,  50],
        [ 70,  90, 110],
        [130, 150, 170]],

       [[190, 210, 230],
        [250, 270, 290],
        [310, 330, 350]],

       [[370, 390, 410],
        [430, 450, 470],
        [490, 510, 530]]])

In [126]:
c = b.reshape((9,3))
c

array([[ 10,  30,  50],
       [ 70,  90, 110],
       [130, 150, 170],
       [190, 210, 230],
       [250, 270, 290],
       [310, 330, 350],
       [370, 390, 410],
       [430, 450, 470],
       [490, 510, 530]])

In [142]:
c[[0,1,2,3,6,5,4,7,8,1],[0,1,2,0,1,2,0,1,2,0]]

array([ 10,  90, 170, 190, 390, 350, 250, 450, 530,  70])

#### Ejercicio 06 :

* Crear el array utilizando los metodos aprendidos en clase

In [16]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])