## Tarea 4 (Marcel)

* Crear el array utilizando los métodos utilizados en clase 

In [2]:
import numpy as np

#### Ejercicio 01 :

In [2]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [47]:
m1=np.full((4,4),6)
np.tril(m1)

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

####  Ejercicio 02 :

Crear un array de 4x4 con valores pares 

In [45]:
m2=np.arange(20,51,2)
m2.reshape(4,4)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50]])

####  Ejercicio 03 :

Crear un array de 4x3 con valores impares

In [34]:
m3=np.arange(15,38,2)
m3.reshape((4,3))

array([[15, 17, 19],
       [21, 23, 25],
       [27, 29, 31],
       [33, 35, 37]])

#### Ejercicio 04 :

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [14]:
m4=np.random.rand(4,4,2)
m4

array([[[0.46371945, 0.77532463],
        [0.17508709, 0.0808513 ],
        [0.40713088, 0.68942355],
        [0.06889923, 0.93091119]],

       [[0.05980189, 0.20861518],
        [0.43844478, 0.04773123],
        [0.50371882, 0.59293732],
        [0.58623302, 0.72867841]],

       [[0.4456549 , 0.37934241],
        [0.81449555, 0.12401664],
        [0.32769045, 0.140385  ],
        [0.80460058, 0.80777213]],

       [[0.53092864, 0.85340652],
        [0.51793661, 0.72739335],
        [0.04284029, 0.30744235],
        [0.06566151, 0.78168617]]])

In [15]:
m4.reshape((8,4))

array([[0.46371945, 0.77532463, 0.17508709, 0.0808513 ],
       [0.40713088, 0.68942355, 0.06889923, 0.93091119],
       [0.05980189, 0.20861518, 0.43844478, 0.04773123],
       [0.50371882, 0.59293732, 0.58623302, 0.72867841],
       [0.4456549 , 0.37934241, 0.81449555, 0.12401664],
       [0.32769045, 0.140385  , 0.80460058, 0.80777213],
       [0.53092864, 0.85340652, 0.51793661, 0.72739335],
       [0.04284029, 0.30744235, 0.06566151, 0.78168617]])

In [16]:
m4.reshape((8,2,2))

array([[[0.46371945, 0.77532463],
        [0.17508709, 0.0808513 ]],

       [[0.40713088, 0.68942355],
        [0.06889923, 0.93091119]],

       [[0.05980189, 0.20861518],
        [0.43844478, 0.04773123]],

       [[0.50371882, 0.59293732],
        [0.58623302, 0.72867841]],

       [[0.4456549 , 0.37934241],
        [0.81449555, 0.12401664]],

       [[0.32769045, 0.140385  ],
        [0.80460058, 0.80777213]],

       [[0.53092864, 0.85340652],
        [0.51793661, 0.72739335]],

       [[0.04284029, 0.30744235],
        [0.06566151, 0.78168617]]])

In [17]:
m4.reshape((2,4,4))

array([[[0.46371945, 0.77532463, 0.17508709, 0.0808513 ],
        [0.40713088, 0.68942355, 0.06889923, 0.93091119],
        [0.05980189, 0.20861518, 0.43844478, 0.04773123],
        [0.50371882, 0.59293732, 0.58623302, 0.72867841]],

       [[0.4456549 , 0.37934241, 0.81449555, 0.12401664],
        [0.32769045, 0.140385  , 0.80460058, 0.80777213],
        [0.53092864, 0.85340652, 0.51793661, 0.72739335],
        [0.04284029, 0.30744235, 0.06566151, 0.78168617]]])

In [22]:
m4.reshape((2,1,16))

array([[[0.46371945, 0.77532463, 0.17508709, 0.0808513 , 0.40713088,
         0.68942355, 0.06889923, 0.93091119, 0.05980189, 0.20861518,
         0.43844478, 0.04773123, 0.50371882, 0.59293732, 0.58623302,
         0.72867841]],

       [[0.4456549 , 0.37934241, 0.81449555, 0.12401664, 0.32769045,
         0.140385  , 0.80460058, 0.80777213, 0.53092864, 0.85340652,
         0.51793661, 0.72739335, 0.04284029, 0.30744235, 0.06566151,
         0.78168617]]])

#### Ejercicio 05 :

Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [4]:
m5=np.arange(3,84,3).reshape(3,3,3)
m5

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[30, 33, 36],
        [39, 42, 45],
        [48, 51, 54]],

       [[57, 60, 63],
        [66, 69, 72],
        [75, 78, 81]]])

In [38]:
m5i=m5.reshape(9,3)
m5i

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54],
       [57, 60, 63],
       [66, 69, 72],
       [75, 78, 81]])

In [39]:
m5i[[0,1,2,3,4,5,6,7,8,3],[0,1,0,0,2,2,1,2,1,0]] #10 elementos

array([ 3, 15, 21, 30, 45, 54, 60, 72, 78, 30])

#### Ejercicio 06 :

* Crear el array utilizando los metodos aprendidos en clase

In [16]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [62]:
m7=np.full((5,5),2)
m7i=np.zeros((3,3))
m7ii=np.array([16])
m7[1:4,1:4]=m7i
m7[2,2]=m7ii
m7

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])