# Tarea 4

## $\color{blue}{\text{Jason Cruz}}$
####  $\color{black}{\text{Usuario Git: Jason18}}$

### Ejercicio 01

* Crear el array utilizando los métodos utilizados en clase

In [1]:
import numpy as np

In [2]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]]) # Hecho por el profesor
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [3]:
# Usando los argumentos start, stop y step
j = np.arange(start = 1,stop = 20,step = 3)
j

array([ 1,  4,  7, 10, 13, 16, 19])

In [4]:
# Creando un array de "strings"
ja=np.array([["the","code","blinders"],["gracias","por","compartir"]])
ja

array([['the', 'code', 'blinders'],
       ['gracias', 'por', 'compartir']], dtype='<U9')

### Ejercicio 02

* Crear un array de 4x4 con valores pares

In [5]:
# Creamos el array de pares utilzando dos funciones: arange() y reshape()
jas1 = np.arange(2,33,2).reshape((4,4))
jas1

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

### Ejercicio 03

* Crear un array de 4x3 con valores impares

In [6]:
# Repetimos lo hecho para el ejercicio 2, pero el argumento start será 1 (impar) para la función arange()
jas2 = np.arange(1,24,2).reshape((4,3))
jas2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

### Ejercicio 04

* Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [7]:
# Usando concatenate()
jas = np.arange(2,33,2).reshape((4,4)) #nuestro primer array (4,4)
on = np.array([[2,4,6,8],[10,12,15,16],[18,20,22,24],[26,28,30,32]]) #nuestro segundo array (4,4)
print(jas) 
print(on)
jason = np.concatenate((jas, on), axis=0) # Obtenemos un array de 32 elemntos porque ahora el array será de la forma (8,4)
jason

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[ 2  4  6  8]
 [10 12 15 16]
 [18 20 22 24]
 [26 28 30 32]]


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [ 2,  4,  6,  8],
       [10, 12, 15, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [8]:
# Primera posible forma
jason.reshape((4,8))

array([[ 2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32],
       [ 2,  4,  6,  8, 10, 12, 15, 16],
       [18, 20, 22, 24, 26, 28, 30, 32]])

In [9]:
# Segunda posible forma
jason.reshape((16,2))

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28],
       [30, 32],
       [ 2,  4],
       [ 6,  8],
       [10, 12],
       [15, 16],
       [18, 20],
       [22, 24],
       [26, 28],
       [30, 32]])

In [10]:
# Tercera posible forma
jason.reshape((1,32))

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
         2,  4,  6,  8, 10, 12, 15, 16, 18, 20, 22, 24, 26, 28, 30, 32]])

In [11]:
# Cuarta posible forma
jason.reshape((32,-1))

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [15],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32]])

### Ejercicio 05

* Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [12]:
# Creamos con la función array() casi manualmente
cod = np.array([[[ 1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24],[25, 26, 27]]])
print(cod)
print(cod.shape) # Comprobamos si es de 3x3x3
print("sí es de 3x3x3")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
sí es de 3x3x3


In [13]:
# Obtenemos 10 elementos de nuestro array

In [14]:
# Primera forma
cod0 = cod.reshape(9,3)
cod00 = cod0[[0,0,0,1,2,3,4,5,6,7],[1,2,2,0,2,1,2,2,2,1]]
print(cod00.size) # Comprobamos que el número de elementos ubicados sea 10 

10


In [15]:
# Segunda forma
cod1 = cod.reshape(1,27)
print(cod1)
# quiero tomar 1,2,3,10,11,12,13,19,20,21
cod2 = cod1[:1,:10] 
print(cod2)
print(cod2.size) # Comprobamos que el número de elementos ubicados sea 10

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27]]
[[ 1  2  3  4  5  6  7  8  9 10]]
10


### Ejercicio 06

* Crear el array utilizando los metodos aprendidos en clase

In [16]:
# Creando un array 
js_1 = np.arange(1,13,2).reshape((2,3))
js_1

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [17]:
# Creamos otro array 
js_2 = np.ones((4,3))
js_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Pero al final, el array que desaba crear es uno que contenga todos los elementos de los 2 primeros (js_1, js_2)
# Por lo tanto, apilaré usando vstack() y obtendré el array "js_objetivo"
js_objetivo = np.vstack((js_1,js_2))
print(js_objetivo)
print(len(js_objetivo)) # Obtenemos la longitud que no es lo mismo que el tamaño (size), la función len me dará el número de clases (filas en este caso)
print(js_objetivo.size) # Este sí es el tamaño, número de elementos del array

[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
6
18


### _The End_

Visiste mi código **"Tarea4_JasonCruz"** en el Git [aquí](https://github.com/antonioalt23/The_Code_Blinders/tree/main/1_Clases/Clase_4/Tarea/Grupo1)