# MÓDULO 2

## 1. NUMPY

* Numpy es un poderoso paquete de Python para manipular estructuras de datos numéricos llamados arrays.<br>
* El objeto básico en NumPy es el array, que es conceptualmente similar a una matriz.<br>
* Los vectores y las matrices son ejemplos de arrays.<br>
* El nombre numpy significa **"Python numérico"**.<br>
* Los numpys son bastante similar a las listas, pero tienen una caracteristica adicional:puede realizar cálculos sobre matrices enteras<br>

 Material de referencia y guia:  ***Applied and Computational Mathematics Emphasis (ACME), Brigham Young University.***


### ***Array Creation***

In [43]:
# importar el paquete numpy 
import numpy as np

In [68]:
# 1-D array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
b = [1,2,4] # lista 
b

[1, 2, 4]

In [46]:
c = np.array([2,3,5,7,11])
c

array([ 2,  3,  5,  7, 11])

In [47]:
# 2-D array
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [48]:
e = np.array([[2,3,4],[5,9,10]])
e

array([[ 2,  3,  4],
       [ 5,  9, 10]])

In [49]:
# 3-d array
f = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,20,23]]])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 20, 23]]])

In [59]:
g = np.array(["hola","peruu"])
g

array(['hola', 'peruu'], dtype='<U5')

In [51]:
h = np.array([True,False])
h

array([ True, False])

In [54]:
i = np.array(["hola","peruuuttt",2,2.5,True])
i 

array(['hola', 'peruuuttt', '2', '2.5', 'True'], dtype='<U9')

### ***Array Atributtes***

| Atributtes | Description |
| -------- | ------------ |
|dtype  |  el tipo de elementos en el array|
|ndim   |  el numero de dimensiones de el array|
|shape  |  una tupla de numeros enteros que<br>indica el tamaño en cada dimesión|
|size |  el numero total de elementos en el array|

In [55]:
# dtype
a.dtype

dtype('int32')

In [57]:
c.dtype

dtype('int32')

In [60]:
g.dtype

dtype('<U5')

In [61]:
i.dtype

dtype('<U9')

In [62]:
# ndim
a.ndim

1

In [63]:
c.ndim

1

In [65]:
d.ndim

2

In [66]:
f.ndim

3

In [69]:
# shape
a.shape

(5,)

In [70]:
a1 = np.array([[2,3],[5,6]])
a1

array([[2, 3],
       [5, 6]])

In [71]:
a1.shape

(2, 2)

In [72]:
f.shape

(2, 2, 3)

In [73]:
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 20, 23]]])

In [74]:
a

array([1, 2, 3, 4, 5])

In [75]:
a.size

5

In [76]:
c

array([ 2,  3,  5,  7, 11])

In [77]:
c.size

5

In [78]:
g

array(['hola', 'peruu'], dtype='<U5')

In [79]:
g.size

2

In [80]:
f.size

12

In [81]:
h = np.array([1,1,1,3])
h

array([1, 1, 1, 3])

In [82]:
h.size

4

In [83]:
lista1 = [1,2,3]
lista1

[1, 2, 3]

In [84]:
lista2 = [4,5,6]
lista2

[4, 5, 6]

In [85]:
lista1 + lista2

[1, 2, 3, 4, 5, 6]

In [86]:
enter = np.array([1,2,3])
enter

array([1, 2, 3])

In [87]:
enter2 = np.array([4,5,6])
enter2

array([4, 5, 6])

In [88]:
enter + enter2

array([5, 7, 9])

In [89]:
lista1*4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [90]:
enter*4

array([ 4,  8, 12])

![Dimensions](https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)
***FUENTE :***    https://indianaiproduction.com/python-numpy-array/

![type_of_matrix](https://www.onlinemathlearning.com/image-files/types-of-matrices.png)

### ***Array Creation Routines***

Numpy nos proporciona una forma eficiente de crear arrays de uso común

|Función|Retorna|
| --- | --- |
|arange( )|array de enteros secuenciales|
|eye( )|2-D array con unos en la diagonal y ceros el resto|
|ones( )|Matriz de forma y tipo dados, llena de unos|
|ones_like( )|array de unos con la misma forma y tipo que una matriz dada|
|zeros( )|array de forma y tipo dados, llena de ceros|
|zeros_like( )|array de unos con la misma forma y tipo que una matriz dada|
|full( )|array de forma y tipo dados, llenos de un valor especificado|
|full_like( )|Matriz completa con la misma forma y tipo que una matriz dada|


Para curiosos :  http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

 numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

El primero de los 3 parametros determina el rango de los valores, mientras el cuarto especifica el tipo de los elementos:

1.**start** es el numero(entero o decimal) que define el primer valor en el array.<br>
2.**stop** es el numero que define el final del array y no está incluido en el array.<br>
3.**step** es el numero que define el espaciamiento(diferencia) entre cada 2 valores consecutivos en el array y el valor predeterminado es 1.<br>
4.**dtype** es el tipo de los elementos de la salida de la matriz y el valor predeterminado es *None*.

In [91]:
peru = np.arange(1,10,2)
peru

array([1, 3, 5, 7, 9])

In [95]:
peru = np.arange(start = 1,stop = 13,step = 5)
peru

array([ 1,  6, 11])

In [96]:
peru_1 = np.arange(1.2,10.9,1)
peru_1

array([ 1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2])

In [98]:
a3 = np.ones((2,3))
a3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
a4 = np.ones((2,2,2))

a4

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [101]:
a5 = np.zeros(5)
a5

array([0., 0., 0., 0., 0.])

In [102]:
a6 = np.zeros((3,6))
a6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [103]:
lead = np.array([[1,2,3],[4,5,6]])
lead

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
#ones_like
lead_1 = np.ones_like(lead)
lead_1

array([[1, 1, 1],
       [1, 1, 1]])

In [105]:
#zeros_like
lead_2 = np.zeros_like(lead)
lead_2

array([[0, 0, 0],
       [0, 0, 0]])

In [107]:
# full
lead_3 = np.full((2,3),7)
lead_3

array([[7, 7, 7],
       [7, 7, 7]])

In [108]:
lead_4 = np.full((2,5),9)
lead_4

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

|Función|Descripción|
|-------|-----------|
| diag() |extrae la diagonal de un array|
| tril() | Obtine la parte triangular inferior de una matriz reemplazando<br> las entradas de arriba de la diagonal con ceros |
| triu() | Obtine la parte triangular superior de una matriz reemplazando<br> las entradas de abajo de la diagonal con ceros |