Roberto Mendoza Matos 

1. Ejercicio numero 01

In [2]:
import numpy as np

In [3]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

2. Crear un array de 4x4 con valores pares

In [4]:
B = np.array([[2,4,8,12],[4,2,24,28],[102,308,100,50],[38,20,10268,2]])
B

array([[    2,     4,     8,    12],
       [    4,     2,    24,    28],
       [  102,   308,   100,    50],
       [   38,    20, 10268,     2]])

3. Crear un array de 4x3 con valores impares

In [5]:
C = np.array([[1,7,9],[11,17,19],[21,27,29],[31,37,39]])
C

array([[ 1,  7,  9],
       [11, 17, 19],
       [21, 27, 29],
       [31, 37, 39]])

4. Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [15]:
vector = np.arange(1,65,2)
vector
# dimension
vector.size

vector1 = print(vector.reshape(4,8))
vector1 = print(vector.reshape(16,2))
vector1 = print(vector.reshape(8,4))
#######################################
vector1 = print(vector.reshape(2,4,4))

[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47]
 [49 51 53 55 57 59 61 63]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]
 [33 35]
 [37 39]
 [41 43]
 [45 47]
 [49 51]
 [53 55]
 [57 59]
 [61 63]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]
 [41 43 45 47]
 [49 51 53 55]
 [57 59 61 63]]
[[[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]
  [25 27 29 31]]

 [[33 35 37 39]
  [41 43 45 47]
  [49 51 53 55]
  [57 59 61 63]]]


5. Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [87]:
matrix3 = np.arange(26,105,3)
matrix3.size

mat = matrix3.reshape(3,3,3)
mat

mat.shape

mat[1,0:3]
np.array([[mat[[1],[0,0,1,1,2],[0,1,0,1,2]]],[mat[[0],[0,0,1,1,2],[0,1,0,1,2]]]])

array([[[53, 56, 62, 65, 77]],

       [[26, 29, 35, 38, 50]]])

6. Crear el array utilizando los metodos aprendidos en clase

In [117]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [115]:
vector1 = np.ones((1,5))*2
vector1

vector2 = np.array([vector1[0,0],0,0,0,vector1[0,0]])
vector2

vector3 = np.array([2,0,16,0,2])
vector3

mat_3 = np.vstack((vector1,vector2,vector3,vector2,vector1))
mat_3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  0., 16.,  0.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

# Solución de Julio Osores
## Ejercicio 01: 
## Construir un array similiar 
## A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])

In [3]:
a = np.full((4,4),6)
a

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [4]:
a_inf = np.tril(a)
a_inf

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

## Ejercicio 02: 
## Crear un array de 4x4 con valores pares

In [5]:
b = np.arange(0,32,2).reshape(4,4)
b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

## Ejercicio 03: 
## Crear un array de 4x3 con valores impares

In [6]:
c = np.arange(1,24,2).reshape(4,3)
c

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

## Ejercicio 04: 
## Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [7]:
d = np.arange(1,64,2)
d
print(d)
d.size

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63]


32

In [8]:
print(d.reshape((2,16)))
print(d.reshape((8,4)))
print(d.reshape((16,-1)))
d.reshape((4,-1))

[[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]
 [41 43 45 47]
 [49 51 53 55]
 [57 59 61 63]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]
 [33 35]
 [37 39]
 [41 43]
 [45 47]
 [49 51]
 [53 55]
 [57 59]
 [61 63]]


array([[ 1,  3,  5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27, 29, 31],
       [33, 35, 37, 39, 41, 43, 45, 47],
       [49, 51, 53, 55, 57, 59, 61, 63]])

## Ejercicio 05: 
## Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [11]:
f = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]],[[10,11,12],[13,14,15],[16,17,18]]])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
f.shape

(3, 3, 3)

In [14]:
f_1 = f[[0,0,1,1,2],[0,0,1,1,2],[[2,1,0,2,0],[0,2,0,1,2]]]
f_1

array([[ 3,  2, -4, -6, 16],
       [ 1,  3, -4, -5, 18]])

In [15]:
f_1.size

10

## Ejercicio 06: 
## Crear el array utilizando los metodos aprendidos en clase 
## tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])

In [16]:
g_1 = np.array([[2,2,2,2,2],[2,0,0,0,2]])
g_2 = np.array([[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
g_3 = np.vstack((g_1,g_2))
g_3

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

# -------------------------------------------------------------------------------------------------------

## Alexander Max Tello Fuentes

### 1

In [2]:
np.tril(np.full((4,4),6))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

### 2

In [3]:
Par = np.arange(2,34,2)
print(Par)
print(np.size(Par))
Par = Par.reshape(4,4)
print(Par)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
16
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


### 3

In [4]:
Impar = np.arange(1,25,2)
print(np.size(Impar))
Impar = Impar.reshape(4,3)
print(Impar)

12
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


### 4

In [5]:
Elementos = np.arange(0,32)
print(Elementos)
np.size(Elementos)
Forma_1 = Elementos.reshape(2,16)
Forma_2 = Elementos.reshape(4,8)
Forma_3 = Elementos.reshape(16,2)
Forma_4 = Elementos.reshape(8,4)

print(Forma_1,Forma_2,Forma_3,Forma_4)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]] [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]] [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### 5

In [6]:
Materia_Prima = np.arange(0,54,2)
print(np.size(Materia_Prima))
Tres_D = Materia_Prima.reshape((3,3,3))
print(Tres_D)
ocho = Tres_D[0,1,1]
doce = Tres_D[0,2,0]
veinte = Tres_D[1,0,1]
catorce = Tres_D[0,2,1]
varios = Tres_D[0:3,0,0]
cuarenta = Tres_D[2,0,2]
otros = Tres_D[0:3,2,1]
print(ocho, doce, veinte, varios,cuarenta, otros)

27
[[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[18 20 22]
  [24 26 28]
  [30 32 34]]

 [[36 38 40]
  [42 44 46]
  [48 50 52]]]
8 12 20 [ 0 18 36] 40 [14 32 50]


### 6

In [3]:
nucleo = np.array([0,16,0])
paso_uno = np.diag(nucleo)
print(paso_uno)
paso_dos = np.concatenate(([[2,2,2]],paso_uno,[[2,2,2]]),axis=0)
print(paso_dos)
paso_tres = np.hstack((np.full((5,1),2),paso_dos,np.full((5,1),2)))
print(paso_tres)

[[ 0  0  0]
 [ 0 16  0]
 [ 0  0  0]]
[[ 2  2  2]
 [ 0  0  0]
 [ 0 16  0]
 [ 0  0  0]
 [ 2  2  2]]
[[ 2  2  2  2  2]
 [ 2  0  0  0  2]
 [ 2  0 16  0  2]
 [ 2  0  0  0  2]
 [ 2  2  2  2  2]]


# -------------------------------------------------------------------------------------------------------


## James Palma

### 1

In [5]:
Ejer1 = np.full((4,4),6)
Ejer1INF = np.tril(Ejer1)
Ejer1INF

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

### 2

In [7]:
Ejer2 = np.zeros((4,4))
Ejer2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3

In [9]:
Ejer3 = np.full((4,3),7)
Ejer3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### 4

In [10]:
Ejer4 = np.arange(1,33,1)
Ejer4RE1 = Ejer4.reshape((4,8))
Ejer4RE2 = Ejer4.reshape((2,16))
Ejer4RE3 = Ejer4.reshape((8,4))
print(Ejer4)
print(Ejer4RE1)
print(Ejer4RE2)
print(Ejer4RE3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


### 5

In [11]:
Ejer5 = np.arange(1,28,1).reshape((3,3,3))
print(Ejer5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


### 6

In [12]:
mat1 = np.diag(np.array([0, 16, 0]))
mat2 = np.array([2, 2, 2])
mat3 = np.array([[2, 2, 2,2,2]])
mat4 = mat3.T

mat5 = np.vstack((mat2,mat1,mat2))
Ejer6 = np.hstack((mat4,mat5,mat4))
Ejer6


array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

ABIGAIL QUISPE 