In [1]:
import numpy as np

In [8]:
A = np.ones((4,4))*6
B= np.tril(A)
B

array([[6., 0., 0., 0.],
       [6., 6., 0., 0.],
       [6., 6., 6., 0.],
       [6., 6., 6., 6.]])

In [16]:
F=np.arange(4,36,2).reshape((4,-1))
F

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [27]:
I=F[:,0:3]-1
I

array([[ 3,  5,  7],
       [11, 13, 15],
       [19, 21, 23],
       [27, 29, 31]])

In [35]:
J=np.arange(2,34,1)
len(F)
J1=J.reshape(16,-1)
J2=J.reshape(8,-1)
J3=J.reshape(4,-1)
J4=J.reshape(2,-1)
print(J1)
print(J2)
print(J3)
print(J4)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]]
[[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]]


In [47]:
DD = np.array([[[1,2,3],[4,5,6],[7,7,7]],[[8,9,10],[11,20,23],[8,7,7]],[[13,14,18],[21,50,73],[7,7,10]]])
DD.shape

(3, 3, 3)

In [45]:
a1=DD[1,2,2]  # Elemento: 7
a2=DD[2,1,0]  # Elemento: 21
a3=DD[1,1,1]  # Elemento: 21
a4=DD[0,0,0]  # Elemento: 1
a5=DD[0,2,2]  # Elemento: 7
a6=DD[1,2,0]  # Elemento: 8
a7=DD[2,2,2]  # Elemento: 10
a8=DD[2,1,2]  # Elemento: 73
a9=DD[2,0,2]  # Elemento: 18
a10=DD[1,0,2]  # Elemento: 10

7

In [53]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [57]:
base_1 = np.array([[2,2,2,2,2],[2,0,0,0,2]])
base_1

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [ ]:
base_2 = np.array([[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
base_2

In [ ]:
tarea_3 = np.concatenate((tarea_1,tarea_2), axis=0 )
tarea_3