In [1]:
import numpy as np 

In [2]:
ss= np.array([[1,5,10],[6,13,15]])
ss

array([[ 1,  5, 10],
       [ 6, 13, 15]])

# TAREA 

# Crear un array con la siguientes Caracteristicas

In [18]:
# Crear una array
A= np.array([[6,0,0,0,],[6,6,0,0],[6,6,6,6]])
A


array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 6]])

In [19]:
A_inf= np.tril(A)
A_inf

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0]])

# Crear un array 4*4 con valores pares

In [17]:
# Crear un array 4*4 con valores pares - Primera forma
B = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])
B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [16]:
O= np.arange(2,34,2).reshape(4,4)
O

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [63]:
O.size

16

In [12]:
# Crear un array 4 *4 con valores pares - Segunda forma
B = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])
B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [20]:
C = np.array([[2,4,6,8],[10,12,14,16]])
C


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [21]:
D = np.array([[18,20,22,24],[26,28,30,32]])
D


array([[18, 20, 22, 24],
       [26, 28, 30, 32]])

In [22]:
F= np.concatenate((C,D),axis =0 )
F

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [23]:
H = np.full((4,4),8)
H

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

# Hacer una matriz 4*3

In [24]:
# Crear una matriz 4*3 con la función concatenate 
G = np.array([[1,5,8],[11,13,15],[17,19,21]])
G


array([[ 1,  5,  8],
       [11, 13, 15],
       [17, 19, 21]])

In [25]:
I =np.array([[1,3,5]])
I

array([[1, 3, 5]])

In [26]:
M= np.concatenate((G,I), axis=0)
M


array([[ 1,  5,  8],
       [11, 13, 15],
       [17, 19, 21],
       [ 1,  3,  5]])

In [5]:
# crear una matriz 4 * 3 con la función arange y reshape
Q = np.arange(1,25,2).reshape(4,3)
Q

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [50]:
M.shape

(4, 3)

In [21]:
I.shape

(1, 3)

# Crear un array con 32 valores y darles diferentes formas

In [22]:
# Crear un array con 32 valores
N= np.arange(2,34,1)
N

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [23]:
N.size

32

In [24]:
N.reshape((2,16))

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [25]:
N.reshape((4,8))

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33]])

In [26]:
N.reshape((8,4))

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [27]:
N.reshape((16,2))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33]])

# Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [28]:
P= np.array([[[1,2,3],[4,5,6],[20,21,22]],[[7,8,9],[10,11,12],[17,18,12]],[[13,14,15],[17,18,19],[18,96,74]]])
P

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [20, 21, 22]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [17, 18, 12]],

       [[13, 14, 15],
        [17, 18, 19],
        [18, 96, 74]]])

In [32]:
P.shape

(3, 3, 3)

In [45]:
P[ [0, 2, 1,0, 1,0,1, 0, 0, 1] , [1 ,2, 1, 2, 1,2, 0, 2, 1, 2], [0, 1, 0, 1, 1, 1, 2, 2, 1 ,1]]

array([ 4, 96, 10, 21, 11, 21,  9, 22,  5, 18])

# Averiguar la forma

In [49]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [13]:
# Primera forma
tarea_1 = np.array([[2,2,2,2,2],[2,0,0,0,2]])
tarea_1

array([[2, 2, 2, 2, 2],
       [2, 0, 0, 0, 2]])

In [53]:
tarea_2 = np.array([[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea_2

array([[ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [54]:
tarea_3 = np.concatenate((tarea_1,tarea_2), axis=0 )
tarea_3

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [11]:
# Segunda froma
tarea_4= np.array([2,0,16,0,2])
tarea_4

array([ 2,  0, 16,  0,  2])

In [15]:
tarea_5=np.vstack((tarea_1,tarea_4,tarea_1))
tarea_5

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2]])