## Tarea 4 :

* Crear el array utilizando los métodos utilizados en clase 

In [47]:
import numpy as np

#### Ejercicio 01 :

In [27]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [28]:
A_inf = np.tril(A)
A_inf

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

####  Ejercicio 02 :

#Crear un array de 4x4 con valores pares

In [10]:
Clavel = np.array([[22,44,66,88],[42,46,68,34],[12,16,24,56],[36,94,63,4]])
Clavel

array([[22, 44, 66, 88],
       [42, 46, 68, 34],
       [12, 16, 24, 56],
       [36, 94, 63,  4]])

In [21]:
Flor = np.full((4,4),22)
Flor

array([[22, 22, 22, 22],
       [22, 22, 22, 22],
       [22, 22, 22, 22],
       [22, 22, 22, 22]])

####  Ejercicio 03 :

Crear un array de 4x3 con valores impares

In [11]:
Bugambilia = np.array ([[33,25,75,11],[99,197,53,71],[15,89,17,3]])
Bugambilia

array([[ 33,  25,  75,  11],
       [ 99, 197,  53,  71],
       [ 15,  89,  17,   3]])

#### Ejercicio 04 :

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [12]:
Natural = np.array (["Girasol","Lluvia","Loto","Campo","Margarita","Cantuta","Monto","Tierra","Mar","Faro","Ave","Barco","Arena","Sol","Cielo","Acuarela","Musica","Estrella","Verano","Chocolate","Pajaro","Arbol","Viaje","Risas","Amigos","Regalo","Abrazo","Rosas","Laguna","Primavera","Amarillo","Ukelele"])
Natural

array(['Girasol', 'Lluvia', 'Loto', 'Campo', 'Margarita', 'Cantuta',
       'Monto', 'Tierra', 'Mar', 'Faro', 'Ave', 'Barco', 'Arena', 'Sol',
       'Cielo', 'Acuarela', 'Musica', 'Estrella', 'Verano', 'Chocolate',
       'Pajaro', 'Arbol', 'Viaje', 'Risas', 'Amigos', 'Regalo', 'Abrazo',
       'Rosas', 'Laguna', 'Primavera', 'Amarillo', 'Ukelele'], dtype='<U9')

In [13]:
Natural = np.array ([["Girasol","Lluvia","Loto","Campo","Margarita","Cantuta","Monto","Tierra"],["Mar","Faro","Ave","Barco","Arena","Sol","Cielo","Acuarela"],["Musica","Estrella","Verano","Chocolate","Pajaro","Arbol","Viaje","Risas"],["Amigos","Regalo","Abrazo","Rosas","Laguna","Primavera","Amarillo","Ukelele"]])
Natural

array([['Girasol', 'Lluvia', 'Loto', 'Campo', 'Margarita', 'Cantuta',
        'Monto', 'Tierra'],
       ['Mar', 'Faro', 'Ave', 'Barco', 'Arena', 'Sol', 'Cielo',
        'Acuarela'],
       ['Musica', 'Estrella', 'Verano', 'Chocolate', 'Pajaro', 'Arbol',
        'Viaje', 'Risas'],
       ['Amigos', 'Regalo', 'Abrazo', 'Rosas', 'Laguna', 'Primavera',
        'Amarillo', 'Ukelele']], dtype='<U9')

In [14]:
Natural = np.array ([["Girasol","Lluvia","Loto","Campo","Margarita","Cantuta","Monto","Tierra","Mar","Faro","Ave","Barco","Arena","Sol","Cielo","Acuarela"],["Musica","Estrella","Verano","Chocolate","Pajaro","Arbol","Viaje","Risas","Amigos","Regalo","Abrazo","Rosas","Laguna","Primavera","Amarillo","Ukelele"]])
Natural

array([['Girasol', 'Lluvia', 'Loto', 'Campo', 'Margarita', 'Cantuta',
        'Monto', 'Tierra', 'Mar', 'Faro', 'Ave', 'Barco', 'Arena', 'Sol',
        'Cielo', 'Acuarela'],
       ['Musica', 'Estrella', 'Verano', 'Chocolate', 'Pajaro', 'Arbol',
        'Viaje', 'Risas', 'Amigos', 'Regalo', 'Abrazo', 'Rosas',
        'Laguna', 'Primavera', 'Amarillo', 'Ukelele']], dtype='<U9')

In [15]:
Natural = np.array ([["Girasol","Lluvia","Loto","Campo"],["Margarita","Cantuta","Monto","Tierra"],["Mar","Faro","Ave","Barco"],["Arena","Sol","Cielo","Acuarela"],["Musica","Estrella","Verano","Chocolate"],["Pajaro","Arbol","Viaje","Risas"],["Amigos","Regalo","Abrazo","Rosas"],["Laguna","Primavera","Amarillo","Ukelele"]])
Natural

array([['Girasol', 'Lluvia', 'Loto', 'Campo'],
       ['Margarita', 'Cantuta', 'Monto', 'Tierra'],
       ['Mar', 'Faro', 'Ave', 'Barco'],
       ['Arena', 'Sol', 'Cielo', 'Acuarela'],
       ['Musica', 'Estrella', 'Verano', 'Chocolate'],
       ['Pajaro', 'Arbol', 'Viaje', 'Risas'],
       ['Amigos', 'Regalo', 'Abrazo', 'Rosas'],
       ['Laguna', 'Primavera', 'Amarillo', 'Ukelele']], dtype='<U9')

In [ ]:
Natural

#### Ejercicio 05 :

Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [42]:
Faro = np.array ([[[4,2,3],[5,7,8],[10,14,15]],[[2,16,1],[20,25,24],[30,35,32]],[[33,36,38],[40,37,41],[44,46,48]]])
Faro

array([[[ 4,  2,  3],
        [ 5,  7,  8],
        [10, 14, 15]],

       [[ 2, 16,  1],
        [20, 25, 24],
        [30, 35, 32]],

       [[33, 36, 38],
        [40, 37, 41],
        [44, 46, 48]]])

In [43]:
Faro.shape

(3, 3, 3)

In [44]:
Faro.size

27

In [50]:
Faro[2,1:2,:2]

array([[40, 37]])

In [ ]:
Faro [[1,2,0,2,2,2,0,1,0,2],[2,1,0,1,2,0,1,2,0,1],[0,1,1,2,]]

#### Ejercicio 06 :

* Crear el array utilizando los metodos aprendidos en clase

In [16]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])