TAREA 4_ BETSY
Ejercicio 1

In [2]:
#Importar el paquete Numpy
import numpy as np

In [5]:
X = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
X

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [6]:
m1=np.full((4,4),6)
np.tril(m1)

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

Ejercicio 2
Crear un array de 4x4 con valores pares

In [7]:
x12=np.array([[2,4],[6,8],[10,12],[14,16]])
x12

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [8]:
y12=np.array([[20,22],[24,26],[28,30],[32,34]])
y12

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [9]:
xy=np.hstack((x12,y12))
xy

array([[ 2,  4, 20, 22],
       [ 6,  8, 24, 26],
       [10, 12, 28, 30],
       [14, 16, 32, 34]])

Ejercicio 3: Crear un array de 4x3 con valores impares

In [10]:
x=np.arange(5,29,2).reshape(4,3)
x

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

Ejercicio 4: Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [11]:
#1° Forma
x=np.arange(2,66,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

In [14]:
#2° Forma
x2=x.reshape(4,8)
x2

array([[ 2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60, 62, 64]])

In [16]:
#3° forma
x3=x.reshape(16,2)
x3

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40],
       [42, 44],
       [46, 48],
       [50, 52],
       [54, 56],
       [58, 60],
       [62, 64]])

In [17]:
#4° Forma
x4=x.reshape(32,1)
x4

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48],
       [50],
       [52],
       [54],
       [56],
       [58],
       [60],
       [62],
       [64]])

Ejercicio 5: Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [18]:
x=np.arange(2,56,2).reshape(3,3,3)
x

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[38, 40, 42],
        [44, 46, 48],
        [50, 52, 54]]])

In [21]:
x[[1,0,1,2,0,2,1,0,2,1],[1,2,2,1,0,1,2,1,0,2],[2,1,2,0,1,2,0,1,0,1]]

array([30, 16, 36, 44,  4, 48, 32, 10, 38, 34])

In [26]:
x=np.arange(4,22,2).reshape(3,3)
x

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [27]:
y=np.arange(3,30,3).reshape(3,3)
y

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [28]:
x+y

array([[ 7, 12, 17],
       [22, 27, 32],
       [37, 42, 47]])