## Grupo 1 - Tarea 4

* Crear el array utilizando los métodos utilizados en clase 

In [1]:
import numpy as np

#### Ejercicio 01 :

In [2]:
A = np.array([[6,0,0,0],[6,6,0,0],[6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

####  Ejercicio 02 :

Crear un array de 4x4 con valores pares 

####  Ejercicio 03 :

Crear un array de 4x3 con valores impares

#### Ejercicio 04 :

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

#### Ejercicio 05 :

Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [73]:
m5=np.arange(3,84,3).reshape(3,3,3)
m5

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]],

       [[30, 33, 36],
        [39, 42, 45],
        [48, 51, 54]],

       [[57, 60, 63],
        [66, 69, 72],
        [75, 78, 81]]])

In [120]:
m5i=slice(0,3,2) #slice(start, end, step)
print(m5[m5i])

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[57 60 63]
  [66 69 72]
  [75 78 81]]]


In [103]:
m5[:3,:1,:3] #9 elementos

array([[[ 3,  6,  9]],

       [[30, 33, 36]],

       [[57, 60, 63]]])

In [122]:
m6=m5.reshape(9,3)
m6

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54],
       [57, 60, 63],
       [66, 69, 72],
       [75, 78, 81]])

In [124]:
m6[[0,1,2,3,4,5,6,7,8,3],[0,1,0,0,2,2,1,2,1,0]] #10 elementos

array([ 3, 15, 21, 30, 45, 54, 60, 72, 78, 30])

#### Ejercicio 06 :

* Crear el array utilizando los metodos aprendidos en clase

In [16]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])